### ISSUE TITLE
(명재문 박선우) 겜프프로젝트 과정평가용(방문기록)

### ISSUE THREAD

**Issue by GGMinwok** [gghteam/Guide_CSharp_Programming#1]
5/26 기록용 잠깐방문/아직 안살펴봤음...

**Comment by GGMinwok** [comment]
6/8 작업내용 - 지금까지 한 것, 오늘 1-3교시에 한 것 구분해서 과정 기록 해주기!

**Comment by anglik0370** [comment]
swith문, while문, for문 파트 작업
작업한 내용은 copy.me를 확인해주시면 감사하겠습니다.

**Comment by GGMinwok** [comment]
copy.me확인함.  copy.md 는 선우꺼고.. 앞에 readme는 재문이꺼니???

**Comment by GGMinwok** [comment]
commit내용 확인함.

**Comment by anglik0370** [comment]
break, continue, goto 작업
작업한 내용은 copy.md를 확인해주시면 감사하겠습니다.

**Comment by GGMinwok** [comment]
6/22 이전주 기록확인
명재문 Readme 확인
박선우 copy 확인

**Comment by GGMinwok** [comment]
박선우... 커밋확인은 하는데 일지라고 하기는...

**Comment by anglik0370** [comment]
enum, struct 파트 작성

**Comment by GGMinwok** [comment]
6/30 검사완료합니다.
